---
title: "PMCMCV4"
output: html_document
---

---
title: "PMCMCV3"
output: html_document
---

```{r}
library(nimble)
library(nimbleSMC)

#---------------------------------------------------
# 1. Define the State Space Model in NIMBLE
#---------------------------------------------------
ssmCode <- nimbleCode({
  x[1] ~ dbin(mu_0, 1)
  y[1] ~ dnorm(x[1], 1)
  
  for(i in 2:T) {
    x[i] ~ dbin(x[i-1] * a + (1 - x[i-1]) * b, 1)
    y[i] ~ dnorm(x[i] * c * cos(3.14159 * i) + (1 - x[i]) * d * cos(3.14159 * i), 1)
  }

  # Priors
  a ~ dunif(0, 1)
  b ~ dunif(0, 1)
  c ~ dnorm(1, 1)
  d ~ dnorm(1, 1)
  mu_0 ~ dunif(0, 1)
})
```

```{r}
# intialize what are the x, y, number of time steps, and the satellite you want to test
#the number of steps
T <- 100
#the starting time step
startT <- 380
#which satellite you want to test
testData <- finalTable(213)
#the nodes you want to test on 
x <- testData$Type_NK[startT:(startT + T - 1)]
y <- testData$Eccentricity[startT:(startT + T - 1)]
#initialize the results table
results_df <- data.frame()
```

```{r}
#set how many interavals of values you want to test
ite <- (max(testData$Eccentricity) - min(testData$Eccentricity)) /10

#Finally input your initial estimates for the specified parameters
init_grid <- expand.grid(
  a = seq(-1, 1, by = 0.2),
  b = seq(-1, 1, by = 0.2),
  c = seq(min(testData$Eccentricity), max(testData$Eccentricity), by =  ite),
  d = seq(min(testData$Eccentricity), max(testData$Eccentricity), by = ite),
  mu_0 = seq(1, 1, by = 0.2)
)
#make list of the parameters
parameters <- c("a", "b", "c", "d", "mu_0")

```

```{r}
#make sure the simulation function matches
simulate_x <- function(a, b, mu_0, T) {
  x <- numeric(T)
  x[1] <- rbinom(1, 1, mu_0)
  for (i in 2:T) {
    prob <- x[i - 1] * a + (1 - x[i - 1]) * b
    x[i] <- rbinom(1, 1, prob)
  }
  return(x)
}
```

```{r}
#make sure the parameters match in this function too
getBest <- function(samples, x_true, T, n = 100) {
  errors <- numeric(n)
  
  for (i in 1:n) {
    params <- samples[i, ]
    x_sim <- simulate_x(params["a"], params["b"], params["mu_0"], T)
    errors[i] <- mean((x_true - x_sim)^2)
  }
  
  best_idx <- which.min(errors)
  best_params <- samples[best_idx, ]
  best_error <- errors[best_idx]
  
  # Combine into a data.frame
  result <- data.frame(as.list(best_params))
  result$error <- best_error
  
  return(result)
}

```


```{r}
for (i in 1:nrow(init_grid)) {
  current_inits <- list(
    x = rbinom(T, 1, 0.5),
    a = init_grid$a[i],
    b = init_grid$b[i],
    c = init_grid$c[i],
    d = init_grid$d[i],
    mu_0 = init_grid$mu_0[i]
  )
  
  samples <- pmcmc(ssmCode, T, startT, x, y, inits, parameters, 100, 1000)
  result_row <- getBest(samples2, x, T, n = 100)
  results_df <- rbind(results_df, result_row)
}

results_sorted <- results_df[order(results_df$error), ]
head(results_sorted)
```





The model for this code:
```{r}
pmcmc <- function(modelCodeInitial, numSteps, startStep, true_x, true_y, initialList, paramList, numParticles, numIter ){
  constants <- list(T = numSteps)
  data <- list(y = true_y)

  model <- nimbleModel(modelCodeInitial, constants = constants, data = data, inits = initialList, check = TRUE)
  cModel <- compileNimble(model)
  
  
  conf <- configureMCMC(model, nodes = NULL)
  
  conf$addSampler(
    target = paramList,
    type = "RW_PF_block",
    control = list(
      latents = "x",
      propCov = diag(length(paramList)),
      pfType = "bootstrap",  # particle filter type
      pfNparticles = numParticles
    )
  )
  
  conf$addMonitors("x") 
  
  mcmc <- buildMCMC(conf)
  cmcmc <- compileNimble(mcmc, project = model)
  
  samples2 <- runMCMC(cmcmc, niter = 1000, nburnin = 200, progressBar = TRUE)
  
  return (samples2)
}
```




